### ISSUE TITLE
EMOJI SUPPORT!

### ISSUE THREAD

**Issue by gu3st** [lolcommits/lolcommits#135]
It's kinda obscure, but supporting Emoji could be fun!

**Comment by smichaelsen** [comment]
It seems like a font without emoji support is used. 😭

**Comment by maxoumime** [comment]
Would also love to see this happen ! At least for the Github emojis ':bug:'.
Maybe we can use a parser like [gemoji-parser](https://github.com/gmac/gemoji-parser) ?

**Comment by matthutchinson** [comment]
I think we're at a point now where changing the default font used is a good idea..  I'll look into finding something that is cross-platform friendly for emoji.  

cc @mroth

**Comment by matthutchinson** [comment]
So I looked into this further today.. It is not as simple as plugging in a new emoji capable font..  We use Imagemagick to annotate the image and (through its use of fontconfig, Cairo and freetype) it is currently not possible to render emoji text. See [here](http://www.imagemagick.org/discourse-server/viewtopic.php?f=1&t=23057&hilit=emoji&start=15) for more info...

**Comment by matthutchinson** [comment]
That said, we could do something smart just for OSX... build a small command line tool in Swift to generate a transparent PNG image with text over laid (I believe that will support emoji chars), then overlay this image on top of the captured photo... 

* https://stackoverflow.com/questions/28906914/how-do-i-add-text-to-an-image-in-ios-swift#28907826
* https://stackoverflow.com/questions/6992830/how-to-write-text-on-image-in-objective-c-ios

**Comment by brianbancroft** [comment]
That would be wonderful. The office where I work incorporates emoji into our commits, so it does add some funky characters into my lolcommits https://gitmoji.carloscuesta.me/

**Comment by matthutchinson** [comment]
re-opening since I would still really like to see this work some day...
