### ISSUE TITLE
--fork results in error with magit (emacs porcelain)

### ISSUE THREAD

**Issue by kleinschmidt** [lolcommits/lolcommits#370]
With the `--fork` option (invoked manually or via the environment variable), lolcommits does not run inside magit (a porcelain for emacs).  Without `--fork` there's no problem.  It creates a .pid file in the repo's `~/.lolcommits` subdirectory, but no image is captured.

I'm on arch linux (4.15.9), emacs 25.3, and lolcommits 0.11.0.  Here's a typical session from the shell:

```
topics-socio-cog on  master [⇡$!?]
➜ lolcommits --capture --fork --debug
Outputting at DEBUG verbosity
Checking for valid vcs repo
Walking up dir tree
GitInfo: parsed the following values from commit:
GitInfo:        use pandoc-crossref instead of fignos/tablenos/eqnos
GitInfo:        e3ae7a4a336
GitInfo:        /home/dave/.dropbox-raizadalab/Dropbox (Raizada Lab)/work/writing/submitted/topics-socio-cog/.git
GitInfo:        kleinschmidt/topics-socio-cog
GitInfo:        master
GitInfo:        2018-03-16 18:38:47 UTC
GitInfo:        Dave Kleinschmidt
GitInfo:        dave.f.kleinschmidt@gmail.com
Capturer: initializing new instance #<Lolcommits::CaptureLinux:0x00005578c4255638>
LinuxCapturer: making tmp directory
LinuxCapturer: calling out to mplayer to capture image

topics-socio-cog on  master [⇡$!?]
➜ LinuxCapturer: calling out to mplayer to capture image
LinuxCapturer: cleaning up
Runner: resizing snapshot
Runner: copying resized image to /home/dave/.lolcommits/topics-socio-cog/e3ae7a4a336.jpg
Runner: loltext is enabled with valid config, running post_capture
Lolcommits::Plugin::Loltext: Annotating image via MiniMagick
Lolcommits::Plugin::Loltext: annotating message to image with use pandoc-crossref instead of
fignos/tablenos/eqnos
Lolcommits::Plugin::Loltext: annotating sha to image with e3ae7a4a336
Lolcommits::Plugin::Loltext: Writing changed file to /home/dave/.lolcommits/topics-socio-cog/e3ae7a4a336.jpg
Runner: running cleanup
```

Same thing when I run in magit w/o `--fork`, but with `--fork` it cuts off after:

```
  4 lolcommits --capture --debug
Outputting at DEBUG verbosity
Checking for valid vcs repo
Walking up dir tree
GitInfo: parsed the following values from commit:
GitInfo: 	testing again
GitInfo: 	26519790dd7
GitInfo: 	/home/dave/.dropbox-raizadalab/Dropbox (Raizada Lab)/work/writing/submitted/topics-socio-cog/.git
```

(I've observed exit status 3, 4, or 5).  What I _suspect_ is happening is that magit is not keeping a permanent shell around but rather shelling out one command at a time and the forked process gets killed when the parent git process is done.  But I'm way out of my depth there, so that could be completely off...

**Comment by kleinschmidt** [comment]
There is apparently an emacs bug that leads to every child process getting a SIGHUP when the parent is finished: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=21866

The local solution is to just put a `nohup` in front of the call to `lolcommits --capture` in the post commit hook, but that feels a little hacky.

**Comment by matthutchinson** [comment]
Going to close since this is an "emacs bug" and there is a work-around (tho it's not pretty I agree).
