### ISSUE TITLE
Transfer this repository to the lolcommits organisation

### ISSUE THREAD

**Issue by matthutchinson** [lolcommits/lolcommits#389]
Tasks required to complete transfer of this repo from [mroth/lolcommits](https://github.com/mroth/lolcommits) to a new repo at [lolcommits/lolcommits](https://github.com/lolcommits/lolcommits).

### Transfer

- [x] Follow [steps](https://help.github.com/en/articles/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account) to transfer the repo at GitHub
- [x] Ensure teams/users/roles are appropriate in lolcommits org after transferring
- [x] ~Create a new mroth/lolcommits repo with a placeholder README.md explaining the move~ Confirm mroth/lolcommits redirects properly

--- 

### Links

- [x] Update any links in the new repo's transferred wiki
- [x] Update any links at [lolcommits.github.io](https://lolcommits.github.io) to the new repo
- [x] Update any links in all [official plugins](https://github.com/lolcommits) to the new repo
  - [x] Release new plugin patch versions for all (since there could be gemspec link updates).
- [x] Submit a PR to [lolcommits-glitch](https://github.com/tooluser/lolcommits-glitch) plugin to update links
- [x] Update links in lolcommits.gemspec and throughout the repo
  - [x] Review changes and release new patch version of lolcommits
- [x] Update any links at [lolcommits-dot-com](https://github.com/lolcommits/lolcommits-dot-com) (heroku hosted gallery app)
- [x] Update link on Twitter account

---

### Misc

- [x] Migrate new lolcommits/lolcommits repo to use [Travis-CI.com](travis-ci.com)
  - [x] Fix badge and links in the new repo to point to travis-ci.com

**Comment by mroth** [comment]
On `Create a new mroth/lolcommits repo with a placeholder README.md explaining the move` my understanding is that GitHub will actually automatically HTTP redirect to the new location, which is nice! (Let's see though)

**Comment by mroth** [comment]
Transferred repo, and confirmed redirects seem to be in place:
```
$ curl --head https://github.com/mroth/lolcommits                            
HTTP/1.1 301 Moved Permanently
Server: GitHub.com
Date: Fri, 26 Apr 2019 17:30:10 GMT
Content-Type: text/html; charset=utf-8
Status: 301 Moved Permanently
Vary: X-PJAX
Location: https://github.com/lolcommits/lolcommits
```

**Comment by mroth** [comment]
As far as I can tell travis-ci.com seems to have been active already. I guess we'll see once we open a PR or push a commit.

**Comment by matthutchinson** [comment]
Yep, I set that up for the lolcommits org earlier in the week, I'll need to update the badge and links in the new repo.

**Comment by matthutchinson** [comment]
I've triggered a [new build](https://travis-ci.com/lolcommits/lolcommits/builds/109802264) via the travis-ci.com dashboard just now.

**Comment by matthutchinson** [comment]
Great that the redirect works, less pressure to update all the links right away. I'll get to that asap.

**Comment by matthutchinson** [comment]
Made some more progress on the list today, should have it wrapped up by end of the weekend.

**Comment by matthutchinson** [comment]
OK, all links updated and tasks complete - closing this one.

Thanks for your help @mroth !
