### ISSUE TITLE
No video devices found after upgrading to catalina (OSX 10.15)

### ISSUE THREAD

**Issue by tristansokol** [lolcommits/lolcommits#397]
I love lolcommits and recently took the plunge to the next OSX version. 

After the upgrade (and related to #395) I switched the  formerly supplied default ruby for brew installed ruby in `/usr/local/bin/lolcommits'. This gave me access to running the lolcommits command again as normal. However, I can't get it to detect any devices. 
```bash 
$ lolcommits --devices
no video devices found.
```
My webcam still appears to work with other apps, so it seems unlikely it is a super coincidental hardware failure. My first thought is that some new privacy settings but when I go into Security & Privacy it seems like `videosnap` has access to my camera (which from what I understand from other issues is what lolcommits uses. 

I think it might still be some kind of permissions/security thing, or maybe my approach to fixing my ruby bug was incorrect. Thank you.

**Comment by one19** [comment]
Sad day indeed, I'm having the same issue.

tried supplying the various names found in: `system_profiler SPCameraDataType`

which returned a few possible options of ids and names and such; none of which worked.

**Comment by matthutchinson** [comment]
So I haven't had time to look into this yet, and I currently don't have a machine capable of running Catalina.  I will try to grab a beta download and install it in a VM to debug further.

#396 is related and may fix the issue, but I can't verify until I have a working copy of Catalina.

**Comment by matthutchinson** [comment]
OK, after a lot of downloading and restarting I have a working Catalina VM, will update with my progress here.

**Comment by matthutchinson** [comment]
OK, can either/both of you try this pre release candidate on Catalina with:

**Comment by tristansokol** [comment]
I installed `0.16.0.pre1` and it works! Thank you so much for your help.

**Comment by matthutchinson** [comment]
Great, will prep a release soon.

**Comment by matthutchinson** [comment]
OK, I've released lolcommits [0.16.0](https://rubygems.org/gems/lolcommits) just now 🚀
