### ISSUE TITLE
Linux webcam resolution

### ISSUE THREAD

**Issue by faan11** [lolcommits/lolcommits#406]
Is there any way to choose the resolution of the image captured?

**Comment by matthutchinson** [comment]
See [here](https://github.com/lolcommits/lolcommits/blob/816caea1cd3ce408211984b05b7d5426ceb81deb/lib/lolcommits/capturer/capture_linux.rb#L18-L22), we use mplayer for capturing on linux.  You can [configure](https://github.com/lolcommits/lolcommits#capture-configuration-options) the capture, but we don't have a resolution option.

If there's a sensible way to pass a resolution arg to mplayer, let me know and I'll see if it can be added.

**Comment by faan11** [comment]
Mplayer has two parameters: width and height

https://linux.die.net/man/1/mplayer

Example:
`mplayer tv:// -tv device=/dev/video0:width=1280:height=720:outfmt=rgb24 -frames 1 -fps 1 -vo jpeg:outdir=test `

**Comment by matthutchinson** [comment]
OK, so to do this either set this ENV var:

    LOLCOMMITS_DEVICE="/dev/video0:width=1280:height=720:outfmt=rgb24"

Or install/enable lolcommits in your repo with the `--device` option like this

    lolcommits --enable --device="/dev/video0:width=1280:height=720:outfmt=rgb24"

**Comment by faan11** [comment]
Thank you, I close this issue
