### ISSUE TITLE
lolcommits dosen't skip capture when rebasing

### ISSUE THREAD

**Issue by ka2n** [lolcommits/lolcommits#417]
Starting with Git 2.18, Git no longer sets `$GIT_DIR` when performing a post-commit hook.
So, lolcommit does not skip the capture when performing a `git rebase`.

**workaround for Linux/macOS users:**

Prepend this to lolcommits hook.

```
GIT_DIR=${GIT_DIR-`git rev-parse --git-dir`}
```

The whole post-commit script looks like this:

```sh
#!/bin/sh

### lolcommits hook (begin) ###
GIT_DIR=${GIT_DIR-`git rev-parse --git-dir`} && LANG="en_US.UTF-8" && PATH="$PATH:<ruby_path>:<imagemagic_path>" && if [ ! -d "$GIT_DIR/rebase-merge" ] && [ "$LOLCOMMITS_CAPTURE_DISABLED" != "true" ]; then lolcommits --fork --capture; fi
###  lolcommits hook (end)  ###
```

Thanks!

**Comment by matthutchinson** [comment]
I've quickly patched [a commit](https://github.com/lolcommits/lolcommits/commit/f3878300b6a37a56ad8868a25769f2b4c0f1dc3c) in to fix this, hopefully can release soon.

**Comment by ka2n** [comment]
@matthutchinson Thank you! I hesitated because I don't have a windows machine.
