### ISSUE TITLE
Can we release a new version

### ISSUE THREAD

**Issue by quintrino** [lolcommits/lolcommits#426]
At the moment the version on Ruby Gems is 0.16.3 - January 28, 2021. 
but this has a vulnerability in git gem  < 1.11.0
But since then the repo has been updated with a new version of git, but that doesn't reflect on Ruby Gems yet. 

Are we able to do a new release on Rubygems?

**Comment by matthutchinson** [comment]
Working on it... been a while since I've worked on this, so might have to bump minimum Ruby versions. I'll hopefully get a release out this/next week.

**Comment by quintrino** [comment]
For anyone also caught by the vulnerability I just added the following line to my gemfile. 

`gem 'lolcommits', :git => 'https://github.com/lolcommits/lolcommits.git'`

**Comment by quintrino** [comment]
@matthutchinson any progress on updating the version on github on to Rubygems.org? 

Github's dependency scan still flags lolcommits as a Critical severity vulnerability.

**Comment by matthutchinson** [comment]
Thanks for the reminder, pushed [0.16.4]( https://rubygems.org/gems/lolcommits) just now.
Somethings up with Travis CI, so for now, I've verified tests pass and gems work locally.
Will switch to GH actions at some point for CI.

Any issues let me know.
